# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#       Take a string that may include parentheses and return a string where any parenthesis is escaped with a back slash.
#
#    For example:
#
#        $escaped = escape_parens('VARCHAR(80)')
#
#        escaped would be 'VARCHAR\(80\)'
#
#
Puppet::Functions.create_function(:'escape_parens') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

    unless args.length == 1
      raise Puppet::ParseError, ("escape_parens(): wrong number of arguments (#{args.length}; must be 1)")
    end

    args[0].gsub('(','\(').gsub(')','\)')
  
  end
end
